### ISSUE TITLE
Why the bruh are dependencies in the git repo

### ISSUE THREAD

**Issue by Parkeymon** [LudosServers/SCPSwap#1]
https://github.com/LudosServers/SCPSwap/tree/1.0.3/SCPSwap

plz remove to save me from death

**Comment by Thundermaker300** [comment]
🤡

**Comment by Parkeymon** [comment]
:trollface:

**Comment by EsserGaming** [comment]
Fixed: [In this commit](https://github.com/LudosServers/SCPSwap/commit/e7478125c43eb3b57eb2a67907ed4ef6429abfc2)

I am peak retard rn :)

**Comment by Parkeymon** [comment]
Only took 2 months :trollface:
